CREATE TABLE IF NOT EXISTS comments (
    id int8 GENERATED by default as identity PRIMARY KEY,
    text varchar(200) not null,
    task_id int8 not null
);

CREATE TABLE IF NOT EXISTS projects (
    id int8 GENERATED by default as identity PRIMARY KEY,
    header varchar(200),
    description varchar(200)
);

CREATE TABLE IF NOT EXISTS users
(
    id  int8 GENERATED by default as identity PRIMARY KEY,
    name  VARCHAR(200),
    password VARCHAR(200),
    email VARCHAR(200),
    role VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id   int8 GENERATED by default as identity PRIMARY KEY,
    header  VARCHAR(200) ,
    description  VARCHAR(200),
    user_id int8,
    date DATE,
    status varchar(255)
);

CREATE TABLE IF NOT EXISTS user_project (
    project_id int8 NOT NULL,
    user_id int8 NOT NULL,
    PRIMARY KEY (project_id, user_id));

INSERT INTO users (name,email, password, role)
VALUES ('Nik','test@ru','$2a$10$ctibGHx86pzJqpPBdIeXKuLDmmH/4JlhD5/jY4DbPSM.nQli2oyum','ROLE_ADMIN'),
       ('test','test@com','$2a$10$ctibGHx86pzJqpPBdIeXKuLDmmH/4JlhD5/jY4DbPSM.nQli2oyum','ROLE_USER');