spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testDB
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
main:
  allow-circular-references: true
  security:
    user:
      name: test
      password: test
      roles: ADMIN
  flyway:
    user: root
    password: root
    default-schema: schema
    baseline-on-migrate: true
    locations: filesystem:migration
    url: jdbc:h2:mem:testdb